import {
  IconApple,
  IconBeer,
  IconBlender,
  IconBottle,
  IconBread,
  IconCandy,
  IconCarrot,
  IconCheese,
  IconChefHat,
  IconCherry,
  IconCherryFilled,
  IconCookie,
  IconCookieMan,
  IconCup,
  IconEgg,
  IconEggFilled,
  IconEggFried,
  IconEggs,
  IconFeather,
  IconFish,
  IconFishBone,
  IconFridge,
  IconGrill,
  IconGrowth,
  IconIceCream,
  IconIceCream2,
  IconLeaf,
  IconLemon,
  IconLemon2,
  IconLollipop,
  IconMeat,
  IconMicrowave,
  IconMilk,
  IconMilkshake,
  IconMug,
  IconMushroom,
  IconMushroomFilled,
  IconPaperBag,
  IconPepper,
  IconPizza,
  IconPlant2,
  IconSalad,
  IconSalt,
  IconSausage,
  IconSeeding,
  IconSoup,
  type TablerIconsProps,
} from "@tabler/icons-react";

export const availableIcons = {
  bread: IconBread,
  carrot: IconCarrot,
  candy: IconCandy,
  cheese: IconCheese,
  chefHat: IconChefHat,
  cherry: IconCherry,
  cherryFilled: IconCherryFilled,
  cookieMan: IconCookieMan,
  cookie: IconCookie,
  blender: IconBlender,
  cup: IconCup,
  egg: IconEgg,
  eggFried: IconEggFried,
  eggFilled: IconEggFilled,
  eggs: IconEggs,
  fishBone: IconFishBone,
  fish: IconFish,
  fridge: IconFridge,
  grill: IconGrill,
  iceCream: IconIceCream,
  iceCream2: IconIceCream2,
  lemon: IconLemon,
  lemon2: IconLemon2,
  lollipop: IconLollipop,
  meat: IconMeat,
  microwave: IconMicrowave,
  milk: IconMilk,
  milkshake: IconMilkshake,
  mushroom: IconMushroom,
  mushroomFilled: IconMushroomFilled,
  paperBag: IconPaperBag,
  pepper: IconPepper,
  pizza: IconPizza,
  salad: IconSalad,
  salt: IconSalt,
  soup: IconSoup,
  sausage: IconSausage,
  apple: IconApple,
  beer: IconBeer,
  bottle: IconBottle,
  mug: IconMug,
  plant2: IconPlant2,
  leaf: IconLeaf,
  seeding: IconSeeding,
  growth: IconGrowth,
  feather: IconFeather,
};
export const Icon = ({
  name,
  ...props
}: TablerIconsProps & { name: keyof typeof availableIcons }) => {
  const IconComponent = availableIcons[name];
  return <IconComponent {...props} />;
};
export type ApiIconProps<T> = TablerIconsProps & { type: T };
